# Generated by Django 4.2.7 on 2023-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolution_valid',
        ),
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('offensive', 'Offensive Content'), ('false_info', 'False Information'), ('illegal_info', 'Illegal info'), ('other', 'Other')], max_length=50),
        ),
    ]
