version: '3' 
services:
  redis: 
    image: "redis:latest"
    container_name: redis
    ports:
      - "6380:6379" 
  mysql:
    image: mysql:8.1
    container_name: mysql 
    environment:
      - MYSQL_DATABASE=seproject
      - MYSQL_ROOT_PASSWORD=se2023
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    expose:
      - "3306" 
    restart: always 
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
    networks:
      - app_network
  app: 
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=HeartFriend.settings_prod
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: > 
      bash -c 
      "python3 manage.py makemigrations && 
      python3 manage.py migrate --settings=HeartFriend.settings_prod && 
      gunicorn -w4 -b 0.0.0.0:8000 --log-level=debug HeartFriend.wsgi &&
      python3 manage.py runserver 0.0.0.0:8000"  
    volumes:
      - ./:/HeartFriend
    expose: 
      - "8000"
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
      - nginx_network 
    env_file:
      - ./.env
  worker:
    container_name: worker
    build: . 
    command: > 
      bash -c "celery -A HeartFriend worker -l INFO"
    volumes:
      - .:/HeartFriend
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0 
    depends_on:
      - app
      - redis 
  beat:
    container_name: beat
    build: . 
    command: > 
      bash -c "celery -A HeartFriend beat -l INFO"
    volumes:
      - .:/HeartFriend
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0 
    depends_on:
      - app
      - redis 
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./media/:/HeartFriend/media/
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - nginx_network

networks:
  app_network:
  nginx_network:
