# Generated by Django 4.2.5 on 2023-12-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='diary',
        ),
    ]
