# Generated by Django 4.2.5 on 2023-12-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_remove_image_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='images',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='diary', verbose_name='image'),
        ),
    ]
