# Generated by Django 4.2.7 on 2023-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allowed_comment',
            field=models.CharField(choices=[('OP', 'Open for comments'), ('CL', 'Closed for comments')], default='OP', max_length=2),
        ),
    ]
