# Generated by Django 4.2.7 on 2023-12-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_post_allowed_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='allowed_comment',
            field=models.CharField(choices=[('OP', 'Open for comments'), ('CL', 'Closed for comments'), ('AU', 'Only author can comment')], default='OP', max_length=2),
        ),
    ]
