# Generated by Django 4.2.7 on 2023-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_pic',
            field=models.ImageField(blank=True, null=True, upload_to='post_title_pics', verbose_name='标题图片'),
        ),
    ]
