# Generated by Django 4.2.7 on 2023-12-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_post_title_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_pic',
        ),
    ]
