# Generated by Django 4.2.7 on 2023-12-05 08:37

import Forum.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_remove_post_title_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Forum.utils.random_postpic_path, verbose_name='image')),
            ],
        ),
    ]
