# Generated by Django 4.2.7 on 2023-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
