# Generated by Django 4.2.7 on 2023-11-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('openID', models.CharField(max_length=80)),
                ('create_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(default=0)),
                ('sex', models.SmallIntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0, help_text='性别，0保密、1男、2女')),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='Authentication.user')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
