# Generated by Django 4.2.5 on 2023-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_alter_user_create_time_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1700586919),
        ),
    ]
