# Generated by Django 4.2.5 on 2023-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0018_remove_user_avatar_alter_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1701620780),
        ),
    ]
