# Generated by Django 4.2.5 on 2023-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(default='单位', max_length=64),
        ),
    ]
