# Generated by Django 4.2.5 on 2023-12-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0003_rename_select_time_medicine_select_time_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='select_time_raw',
            new_name='select_time',
        ),
    ]
