name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        APPID: ${{ secrets.APPID }}
        APPSECRET: ${{ secrets.APPSECRET }}
        TEST: ${{ secrets.TEST }}
      run: |
        echo "AppID=$APPID\n" > .env
        echo "AppSecret=$APPSECRET\n" >> .env
        echo "TEST=$TEST\n" >> .env
        python manage.py makemigrations 
        python manage.py migrate
        python manage.py test
